### ISSUE TITLE
Update hashValues to Object.hash(...)

### ISSUE THREAD

**Issue by stan-at-work** [letsar/flutter_sticky_header#99]
In the next flutter version the function hashValues will be removed and your package won't work anymore.

Please update hashValues to Object.hash(...) in the override of your hashCode at **SliverStickyHeaderState**

ref: https://api.flutter.dev/flutter/dart-ui/hashValues.html

![image](https://github.com/user-attachments/assets/30843ee0-7251-488d-ab74-dc56cbd3e294)

![image](https://github.com/user-attachments/assets/f17c1bce-8be4-4418-87aa-94bbedc2f328)

**Comment by esentis** [comment]
When will this be released ??

**Comment by stan-at-work** [comment]
> When will this be released ??

Flutter 3.27 just released so this packages is not officialy fucked.

This needs to be fixed ASAP

**Comment by stan-at-work** [comment]
@letsar  Please upload the latest version to pub.dev FAST

**Comment by esentis** [comment]
@stan-at-work Ok 0.7.0 does resolve the issue, try `flutter pub upgrade` to also update the `pubspec.lock` file. Then do a `flutter clean && flutter pub get` and you will be good to go.

**Comment by stan-at-work** [comment]
Thanks @esentis

**Comment by saropa** [comment]
Thanks - I appreciate your package!

**Comment by letsar** [comment]
> > When will this be released ??
> 
> Flutter 3.27 just released so this packages is not officialy fucked.
> 
> This needs to be fixed ASAP

Hi @stan-at-work, this has been released in the 0.7.0 two months ago, so you should get a DeLorean DMC-12 VERY FAST to come back to the present in order to have the update :wink:
<img width="855" alt="image" src="https://github.com/user-attachments/assets/dd0f2677-2f1d-4377-8c60-bf6b0b4d3500" />
<img width="847" alt="image" src="https://github.com/user-attachments/assets/22cedcd4-41bb-4d27-bd73-85939010dc13" />

**Comment by saropa** [comment]
It's strange — I have def been running 0.70 (cleaned and latest and all that, ofc) many times in the last month. Yet, it just blew up today with the new flutter release. stan-at-work could have been nicer, but is prob dealing with flutter blowing up a project today... as it did our project! For now, we have had to remove the dep on flutter_sticky_header

**Comment by stan-at-work** [comment]
> It's strange — I have def been running 0.70 (cleaned and latest and all that, ofc) many times in the last month. Yet, it just blew up today with the new flutter release. stan-at-work could have been nicer, but is prob dealing with flutter blowing up a project today... as it did our project! For now, we have had to remove the dep on flutter_sticky_header

@letsar @saropa 

Oops sorry 😣 i was a bit to hard.

**Comment by letsar** [comment]
I can understand the frustration but I cannot stand this kind of attitude. We, Open Source maintainers, are also humans. We also have a job, we also need to sleep, we also have a personal life, but we are not someone's slave. We don't have to obey someone because we were kind enough to share code that this person chose to add as a dependency to their project. Do you think this kind of comment makes us want to help the person who wrote it? Spoiler alert: No!

I also had projects broken due to a dependency, and I know I will have it again in the future. When the project is Open Source and has a permissive licence, if I cannot wait, I fork the project, fix it by myself and then do a PR to the project. And in the meantime I depend on my fork until my PR is merged. Is it ideal? No, I know it, but it is the responsibility I took when I chose to depend on the project.
